registrycreated=Μητρώο που είχε δημιουργηθεί
badtown=Όνομα απίθανο πόλη
tradeStamp=σφραγίδα
trades=Επαγγέλματα
statement=Δήλωση
filetoolarge=Το αρχείο είναι υπερβολικά μεγάλο
currencyinactive=Νόμισμα ανενεργό
january=Ιανουαρίου
category=Κατηγορία
tradeAmount=ποσό
offered=προσφέρονται
telephone=Τηλέφωνο
cclitecfinsecure=cclite.cf είναι εγγράψιμος, αυτό είναι πολύ επισφαλής, please change
subject=Αντικείμενο
js-portugese=Πορτογαλικό
categorynameexists=Δημιουργία απορρίφθηκε&lt;br&gt;Όνομα κατηγορίας υπάρχει
smspinchanged=Νέος σας αριθμός pin είναι τώρα έτοιμο για χρήση
js-started=Εκκίνηση
newinstall=Αυτή είναι μια νέα εγκατάσταση: θα δημιουργηθεί cclite.cf
remotepartnerinactive=Απομακρυσμένο συνεργάτη κατάστασης είναι ανενεργό
nocrossregistry=Καμία συναλλαγή πολλαπλής μητρώα επιτρέπεται για μαζική
all=όλα
admemail=admin Email
openidadded=Άνοιγμα αναγνωριστικό προστεθεί
december=Δεκεμβρίου
pleasechangeit=άλλαξέ το όταν φτάσετε αυτό!
transactions=συναλλαγές
js-erroris=Το σφάλμα είναι
forvalue=για τιμή
noremotepartner=Δεν απομακρυσμένο συνεργάτη που βρέθηκαν
justprocessed=Μόλις η επεξεργασία
nosysaccount=Παρακαλώ βρεθεί καμία λογαριασμό συστήματος, δημιουργήστε ένα
registryclosing=Μητρώο χαρακτηρίζονται από το κλείσιμο, δεν νέες συνδέσεις
tradeDate=Ημερομηνία
fileuploaded=Αρχείο έχει γίνει upload
js-japanese=Ιαπωνικά
nocsvdir=δεν υπάρχει ή δεν είναι εγγράψιμη
js-lgoff=Αποσύνδεση
no=Όχι
july=Ιουλίου
display=Εμφάνιση
clicktocollapse=Κάντε κλικ στην εντολή για την επιστροφή σε μεγάλες κατηγορίες
smsnodestination=Κανένας χρήστης sms προορισμού δεν βρέθηκε
mustgotocash=Μετρητά πρέπει να πιστωθούν στο λογαριασμό χρήμα μόνο
in=στο
cannotbewritten=δεν είναι δυνατό να εγγραφεί στο
tradeDescription=περιγραφή
js-novolumedata=Δεν υπάρχουν δεδομένα όγκου
may=Μπορεί να
needpin=Χρειάζεται αριθμό PIN και επιβεβαίωση αριθμού PIN
goodbye=Αντίο
heresyourpassword=Here\ του τον κωδικό πρόσβασής σας στο
directorypageadded=Προσθήκη καταλόγου σελίδας
smspinactive=Αριθμός PIN ελέγχεται στο κουμπί ok: σας λογαριασμός είναι ενεργός!
pleasenote=Παρακαλώ Σημειώστε ότι ο νέος σας λογαριασμός δημιουργείται και μπορεί να ενεργοποιηθεί από θα:
js-nobalancedata=Δεν υπάρχουν δεδομένα ισορροπία
smslocked=Κλειδωμένος λογαριασμός για τον sms: Επικοινωνήστε με το διαχειριστή σας για να ξεκλειδώσετε!
languagechanged=Αλλάξει γλώσσα
tradeStatus=κατάσταση
js-processing=Επεξεργασία
js-stopped=Διακόπηκε
invaliddate=μη έγκυρη ημερομηνία
currencysymbolerror=σφάλμα σύμβολο νομίσματος
filenotuploaded=Το αρχείο δεν αποστέλλονται
om_users=Οι χρήστες
js-thai=Ταϊλανδικά
isuniquename=είναι ένα μοναδικό όνομα
userinfofor=Πληροφορίες χρήστη για
userLang=γλώσσα
february=Φεβρουαρίου
js-mustbecsv=Σφάλμα πρέπει να είναι αρχείο τύπου csv
mailtransactionresult=αποτέλεσμα συναλλαγών αλληλογραφίας
notadebit=δεν μια συναλλαγή χρέωσης
newpassword=Ο νέος κωδικός πρόσβασης cclite
usetags=Χρησιμοποιήσετε τις ετικέτες ελεύθερης μορφής παρακάτω
merchantkeyerror=εμπορικά βασικό σφάλμα
emailexists=Ηλεκτρονικό ταχυδρομείο υπάρχει, πρέπει να είναι μοναδικό
overservicechargelimit=Επιπλέον χρέωση υπηρεσιών είναι μεγαλύτερη από το ρυθμισμένο όριο
mobphoneexists=Αριθμός κινητού τηλεφώνου που ανήκει σε κάποιον άλλο, πρέπει να είναι μοναδικό
badstreet=Όνομα unlikely street
currencyrejected=Δημιουργία απορρίφθηκε&lt;br&gt;Το όνομα του νομίσματος υπάρχει
configurationupdated=Ρύθμιση παραμέτρων updated
description=Περιγραφή
tradeItem=το στοιχείο
badpostcode=Ακατάλληλη μορφή Ταχυδρομικός κώδικας
tradeId=αναγνωριστικό
tradeMirror=καθρέφτης
smslanguagechanged=Γλώσσας άλλαξε σε
november=Νοεμβρίου
pages=Σελίδες
batchtransaction=Δέσμης συναλλαγής: βλέπε περιγραφή
invalidcurrency=μη έγκυρο νόμισμα
october=Οκτωβρίου
viagpgemail=Μέσω Email ΠΔΑ:
smssuspend=λογαριασμός ανασταλεί, επικοινωνήστε με το διαχειριστή
ipaddressnotfound=Αυτή η διεύθυνση IP δεν βρίσκεται στη λίστα των διευθύνσεων ip που επιτρέπεται
viabatch=Μέσω δέσμης:
newpassword1=νέος κωδικός πρόσβασης
js-spanish=Ισπανικά
error=για κατά λάθος
badcommitlimit=Δέσμευση όριο πρέπει να είναι αριθμητικό
noencryptednotification=κοινοποίηση: Κρυπτογράφηση κλειδιού λείπει ή μη έγκυρο
js-korean=Κορεατικά
userEmail=ηλεκτρονικό ταχυδρομείο
during=κατά τη διάρκεια
js-searchtrades=Αναζήτηση επαγγέλματα
openiderror=Ανοίξτε το αναγνωριστικό σφάλματος:
passwordfailedfor=κωδικός πρόσβασης απέτυχε για
openIdDesc=Ανοίξτε το αναγνωριστικό περιγραφή
js-admintab=Καρτέλα "Διαχείριση"
bademail=Μη έγκυρη διεύθυνση ηλεκτρονικού ταχυδρομείου
unknowncurrency=Άγνωστη νόμισμα
js-avg=AVG συναλλαγή μέγεθος
js-russian=Ρωσικά
new=Νέα
nosource=Δεν λογαριασμού προέλευσης για συναλλαγή
tryagain=Δοκίμασε ξανά?
emailnotfound=Ηλεκτρονικό ταχυδρομείο δεν βρέθηκε
show=Εμφάνιση
js-user=Cclite χρήστη
js-vietnamese=Βιετναμικά
notanadmin=Δεν είστε ο διαχειριστής
invalidaccount=πρέπει να περιέχουν a-z, μόνο 1-9
js-german=Γερμανικά
balance=Υπόλοιπο
price=Τιμή
fieldvalueplease=τιμή του πεδίου παρακαλώ
batchfileproblems=Αυτά τα αρχεία δέσμης έχουν προβλήματα, χρησιμοποιήστε το ποντίκι συμβουλής εργαλείου για να δείτε:
directorylisting=Λίστα καταλόγων
rdfupdate=Ενημερώθηκε τροφοδοσίες RSS σε
zerovaluetransaction=μηδενική αξία συναλλαγής δεν επιτρέπεται
invalidlogin=Το όνομα χρήστη περιέχει διαστήματα ή χαρακτήρες, απαγορευμένη
transactionstatusnow=Η κατάσταση της συναλλαγής είναι τώρα
isnotactive=δεν είναι ενεργό: επιβεβαίωση ή επικοινωνήστε με το διαχειριστή
smstransactionemailtitle=Συναλλαγή Cclite SMS
js-searchads=Διαφημίσεις αναζήτησης
april=Απριλίου
om_categories=Κατηγορίες διαφημίσεων
tradeCurrency=νόμισμα
js-running=Εκτέλεση
modify=Τροποποίηση
pinconfirmdifferent=PIN και η επιβεβαίωση του PIN πρέπει να είναι το ίδιο
unknownrecipient=Άγνωστο παραλήπτη
mysqlnotrunning=MySQL πιθανώς δεν εκτελείται, ξεκινήστε διακομιστή
usernameis=Είναι το όνομα χρήστη σας
js-arabic=Αραβικά
invalidreceiving=μη έγκυρος χρήστης παραλαβής
tradepartner=Εμπορικός εταίρος
badcurrencyname=Μη έγκυρο νόμισμα όνομα, μία λέξη, πρέπει να αρχίζουν με γράμμα
moneyout=Χρήματα Out
om_yellowpages=Κατάλογος
partnerexists=Τον συνεργάτη μητρώου υπάρχει ήδη
currencycreated=Νόμισμα που δημιουργήθηκε
badproxyname=Διακομιστής μεσολάβησης πρέπει να είναι της μορφής http://domain/cgi-bin/ccserver.cgi
js-bengali=Βεγγαλικά
userName=Εμφανιζόμενο όνομα
incompletetransaction=η συναλλαγή έχει στοιχεία που λείπουν
postpass=καταχώρηση κωδικού πρόσβασης ηλεκτρονικού ταχυδρομείου
count=Καταμέτρηση
followingregistries=Οι ακόλουθες γραμματείες είναι εντός αυτή η εμφάνιση διακομιστή
passwordnotsame=Κωδικός πρόσβασης και επιβεβαίωση πρέπει να είναι η ίδια
js-noaveragesdata=Δεν υπάρχουν δεδομένα μέσους όρους
partneradded=Μητρώο συνεργάτη, δημιουργήθηκε
invalidsending=αποστολή μη έγκυρος χρήστης
delete=Διαγραφή
js-vols=Τόμοι συναλλαγής
notallowedsysaccount=δεν επιτρέπεται για λογαριασμούς συστήματος
tradeSource=από
smstransactiontitle=SMS συναλλαγής
fixed=Σταθερές
js-searchusers=Αναζήτηση χρηστών
smsthebalancefor=Το υπόλοιπο για
js-italian=Ιταλικά
js-adminmenu=Admin μενού
mobile=Mobile
is=είναι
found=Βρέθηκαν
categorycreated=Κατηγορία δημιουργήθηκε
nonexist=Ανύπαρκτα προορισμού
registryopen=Μητρώο σημανθεί ως ανοιχτή, επιτρέπονται συνδέσεις
ok=Ok
recordswith=εγγραφές με
pinobvious=PIN πολύ προφανείς: δεν ακολουθίες
om_currencies=Νομίσματα
previousbalancesare=Οι προηγούμενες υπολοίπων
tradeDestination=για να
batchtrans=Μαζική συναλλαγές
pinsamenumbers=Don\'t χρησιμοποιείτε σύνολα τους ίδιους αριθμούς το ΡΙΝ σας
moneyin=Χρήματα σε
badregistryname=Μη έγκυρη μητρώου, μία λέξη, πρέπει να αρχίζουν με γράμμα
invalidlanguage=Δεν επιλεγείσα γλώσσα χρήστη
needa=Χρειάζεται ένα
js-dutch=Ολλανδικά
js-french=Γαλλικά
wanted=ήθελε
update=Η ενημερωμένη έκδοση
clicktoexpand=Κάντε κλικ για να δείτε περισσότερα
hi=Γεια σου
passwordgesix=Κωδικός πρόσβασης πρέπει να είναι περισσότερο από έξι χαρακτήρες
js-english=Αγγλικά
smsnumbernotfound=ο αριθμός του κινητού δεν βρέθηκε
js-chinese=Κινεζικά
registryexists=Υπάρχει μητρώου, επιλέξτε ένα άλλο όνομα
transactionaccepted=Συναλλαγή αποδεκτή
smsunconfirmedpin=Λήψη μη επιβεβαιωμένες pin χρήστη, δεν είναι ενεργή
march=Μαρτίου
viajabber=Μέσω Jabber:
split=διαίρεση
notregisterederror=πελάτης δεν cclite εγγεγραμμένοι σφάλμα
forsale=Προς πώληση
smsmessageblank=Το μήνυμα SMS είναι κενό
transactionrejected=Συναλλαγή απορρίφθηκε
active=για δραστικές
noregistriesfound=Δεν γραμματείες προς το παρόν, παρακαλώ Δημιουργήστε ένα!
sha1warning=Ο τύπος κλειδιού κατακερματισμού είναι SHA1: δεν εγκαταστήσετε SHA2 αν είναι δυνατόν, μπορεί να αλλάξει μετά την εγκατάσταση
js-greek=Ελληνικά
passwordnelogin=Κωδικός πρόσβασης δεν πρέπει να είναι το ίδιο με σύνδεση
nolocalcurrency=Νόμισμα δεν στο τοπικό μητρώο
loginfailedfor=η σύνδεση απέτυχε για
tradeTaxflag=σημαία του φόρου
admpass=admin κωδικού πρόσβασης
js-romainian=Ρουμανικά
tradeHash=hash
pleaseactivate=Παρακαλούμε να ενεργοποιήσετε το λογαριασμό σας νέα Cclite
youare=Είστε
sameaccount=Δεν είναι δυνατή η μεταφορά για ίδιο λογαριασμό
openId=Ανοίξτε το αναγνωριστικό
tradevolumes=Όγκου των εμπορικών συναλλαγών κατά μήνα&lt;br&gt;(inc. αναμονής/άνοιγμα κ.λπ....)
userLogin=σύνδεση όνομα
doesnotexist=δεν υπάρχει
august=Αύγουστος
notadmin=Όχι διαχειριστής έξοδο
reject=Όχι!
js-fileprocessed=Αρχείο που υποβάλλονται σε επεξεργασία
om_partners=Μητρώο εταίρους
clear=Σαφής
tradeType=Τύπος
transactionlimitexceeded=Η συναλλαγή είναι μεγαλύτερο από το όριο για το εν λόγω μητρώο
smsbadjoin=δεν είναι δυνατό να αναλυθεί σύνδεσμο δεδομένων
baduriname=URI πρέπει να της φόρμας http://domain/Cclite
smsdebitfor=SMS χρέωσης για
servicechargeapplied=Επιπλέον χρέωση υπηρεσιών εφαρμόζονται
om_openid=Άνοιγμα αναγνωριστικά
wrongdbversion=Αναβάθμιση της βάσης δεδομένων να 4.0 ή παραπάνω απαιτείται:
smsinvalidsyntax=Μη έγκυρο μήνυμα πληρωμή SMS
suppliedwhen=και ο κωδικός πρόσβασης είναι εκείνη που δώσατε κατά την εγγραφή.
postemail=δημοσίευση του διακινήσεις Email
userinactive=Χρήστης ανενεργό
chargetype=Χρέωση μοντέλο
dbpasswordorser=Βάση δεδομένων τον κωδικό πρόσβασης ή το χρήστη όνομα πρόβλημα:
smssetupnumberinuse=το πρόγραμμα Εγκατάστασης απέτυχε, αυτό το τηλέφωνο είναι ήδη καταχωρημένο αριθμό
currency=Νόμισμα
userexists=Χρήστης Exists, Παρακαλώ επιλέξτε κάποιο άλλο
smspinfail=Μη έγκυρο αριθμό PIN: please try again!
validaccountname=είναι ένα έγκυρο και αποκλειστικό όνομα
useradded=Χρήστης προσθέσει
smsnopindetected=Αριθμός pin δεν βρεθεί, χρειάζεται ένα pin!
js-waiting=Σε αναμονή
passwordsent=Κωδικός πρόσβασης που αποστέλλεται στην ηλεκτρονική σας διεύθυνση (θα μπορούσε να φάκελο Ανεπιθύμητη αλληλογραφία!!!)
om_registry=Περιγραφή του μητρώου
accepted=για αποδοχή
not_accepted=για δεν γίνει δεκτή
nonexistentpartner=Εταίρος μητρώου δεν υπάρχει
smsnoorigin=Κανένας χρήστης Αποστολή sms που βρέθηκαν
invalidregistry=Μητρώο δεν είναι έγκυρη
js-admin=Cclite admin
tradeTitle=Τίτλος
smsoriginblank=Καταγωγής, ο αριθμός τηλεφώνου δεν βρέθηκε
putcursoron=Θέσει δρομέα σε αριθμό για να λάβετε διαφημίσεων Τίτλος
mailtransactions=αλληλογραφίας συναλλαγών
blankregistry=κενό μητρώου
badphone=Μη έγκυρος αριθμός για το κινητό τηλέφωνο
matched=αντιστοίχιση
unknownregistry=Άγνωστο σφάλμα μητρώου ή βάσης δεδομένων
per=ανά
noremotecurrency=Νόμισμα δεν στο απομακρυσμένο μητρώο
cancel=Άκυρο
loginfirst=Παρακαλούμε, εισέλθετε στο πρώτο!
regmanager=Διαχείριση μητρώου
september=Σεπτεμβρίου
unknownsender=Άγνωστος αποστολέας
nowlogonandcreate=Σύνδεση ως διαχειριστή τώρα και να δημιουργήσετε ένα νόμισμα
fileempty=Κενό αρχείο
js-batchfileprobs=Αρχεία δέσμης ή τους παρακάτω καταλόγους έχουν προβλήματα, να του ποντικιού να εξετάσει
statsupdate=Στατιστικά ενημέρωση στις
smserror=Παρουσιάστηκε σφάλμα SMS
manufacturererror=σφάλμα του κατασκευαστή
confirm=Επιβεβαίωση
at=σε
postcode=Ταχυδρομικός κώδικας
js-balances=Υπόλοιπα
ccinstallinsecure=ccinstall.CGI παρόντες και εκτελέσιμο, αυτό είναι πολύ επισφαλής, please remove
configordbproblem=το πρόβλημα ρύθμισης παραμέτρων ή βάσης δεδομένων: λάθος χρήστη ή τον κωδικό πρόσβασης;
isnowactive=είναι τώρα ενεργή
ccsoapserverinsecure=ccserver.CGI παρόντες και εκτελέσιμο, αυτό είναι επισφαλής, please remove εκτός εάν χρησιμοποιηθεί
openidnotfound=Ανοίξτε το αναγνωριστικό δεν βρέθηκε στο μητρώο
june=Ιουνίου
usepassword=Διορθώστε διαδρομή όνομα_χρήστη/κωδικός_πρόσβασης σε cclite.cf βάση δεδομένων
viamail=Μέσω Email:
