registrycreated=Μητρώο που είχε δημιουργηθεί
badcurrencyname=Μη έγκυρο νόμισμα όνομα, μία λέξη, πρέπει να αρχίζει με γράμμα
tradepartner=Εμπορικός εταίρος
invalidreceiving=μη έγκυρη παραλαβής χρήστη
badtown=Όνομα απίθανο πόλη
partnerexists=Τον συνεργάτη μητρώου υπάρχει ήδη
om_yellowpages=Directory
tradeStamp=σφραγίδα
currencycreated=Νόμισμα που δημιουργήθηκε
trades=Επαγγέλματα
badproxyname=Διακομιστής μεσολάβησης πρέπει να είναι της μορφής http://domain/cgi-bin/ccserver.cgi
currencyinactive=Νόμισμα που θα ανενεργός
january=Ιανουαρίου
incompletetransaction=η συναλλαγή έχει στοιχεία που λείπουν
userName=Εμφανιζόμενο όνομα
tradeAmount=ποσό
postpass=καταχώρηση κωδικού πρόσβασης ηλεκτρονικού ταχυδρομείου
offered=προσφέρονται
passwordnotsame=Ο κωδικός πρόσβασης και επιβεβαίωση πρέπει να είναι η ίδια
followingregistries=Οι ακόλουθες γραμματείες είναι εντός αυτή η εμφάνιση διακομιστή
count=Καταμέτρηση
telephone=Τηλέφωνο
cclitecfinsecure=cclite.cf είναι εγγράψιμος, αυτό είναι πολύ επισφαλής, please change
partneradded=Μητρώου συνεργάτη, δημιουργήθηκε
invalidsending=μη έγκυρη αποστολής χρήστη
categorynameexists=Δημιουργία απορρίφθηκε&lt;br&gt;Όνομα κατηγορίας υπάρχει
smspinchanged=Νέος σας αριθμός pin είναι τώρα έτοιμο για χρήση
userStatus=κατάσταση
delete=Διαγραφή
notallowedsysaccount=δεν επιτρέπεται για λογαριασμούς συστήματος
newinstall=Αυτή είναι μια νέα εγκατάσταση: θα δημιουργηθεί cclite.cf
smstransactiontitle=SMS συναλλαγής
tradeSource=από
remotepartnerinactive=Απομακρυσμένο συνεργάτη κατάστασης είναι ανενεργό
smsthebalancefor=Το υπόλοιπο για
nocrossregistry=Καμία συναλλαγή πολλαπλής μητρώα επιτρέπεται για μαζική
all=όλα
categorycreated=Κατηγορία δημιουργήθηκε
found=Βρέθηκαν
is=είναι
admemail=admin Email
nonexist=Ανύπαρκτα προορισμού
ok=Ok
december=Δεκεμβρίου
pleasechangeit=Αλλάξτε τον όταν φτάσετε αυτό!
recordswith=εγγραφές με
transactions=συναλλαγές
pinobvious=PIN πολύ προφανείς: δεν ακολουθίες
om_currencies=Νομίσματα
forvalue=για τιμή
noremotepartner=Δεν απομακρυσμένο συνεργάτη που βρέθηκαν
batchtrans=Μαζική συναλλαγές
nosysaccount=Παρακαλώ βρεθεί καμία λογαριασμό συστήματος, δημιουργήστε ένα
tradeDestination=για να
pinsamenumbers=Don\'t χρησιμοποιείτε σύνολα τους ίδιους αριθμούς στο σας PIN
tradeDate=Ημερομηνία
invalidlanguage=Δεν επιλεγείσα γλώσσα χρήστη
badregistryname=Μη έγκυρη μητρώου, μία λέξη, πρέπει να αρχίζει με γράμμα
needa=Χρειάζεται ένα
wanted=ήθελε
clicktoexpand=Κάντε κλικ για να δείτε περισσότερα
hi=Γεια σου
passwordgesix=Ο κωδικός πρόσβασης πρέπει να είναι περισσότερο από έξι χαρακτήρες
smsnumbernotfound=ο αριθμός του κινητού δεν βρέθηκε
no=Όχι
july=Ιουλίου
display=Εμφάνιση
clicktocollapse=Κάντε κλικ στην εντολή για την επιστροφή σε μεγάλες κατηγορίες
smsunconfirmedpin=Λήψη χρήστη μη επιβεβαιωμένες pin, δεν είναι ενεργή
smsnodestination=Κανένας χρήστης sms προορισμού δεν βρέθηκε
transactionaccepted=Συναλλαγή αποδεκτή
registryexists=Υπάρχει μητρώου, επιλέξτε ένα άλλο όνομα
march=Μαρτίου
mustgotocash=Μετρητά πρέπει να πιστωθούν στο λογαριασμό χρήμα μόνο
in=στο
viajabber=Μέσω Jabber:
cannotbewritten=δεν είναι δυνατό να εγγραφεί στο
split=διαίρεση
notregisterederror=πελάτης δεν cclite εγγεγραμμένοι σφάλμα
tradeDescription=περιγραφή
may=Μπορεί να
smsmessageblank=Το μήνυμα SMS είναι κενό
forsale=Προς πώληση
needpin=Χρειάζεται αριθμό PIN και επιβεβαίωση αριθμού PIN
active=για δραστικές
transactionrejected=Συναλλαγή απορρίφθηκε
noregistriesfound=Δεν γραμματείες προς το παρόν, παρακαλώ Δημιουργήστε ένα!
goodbye=Αντίο
sha1warning=Ο τύπος κλειδιού κατακερματισμού είναι SHA1: δεν εγκαταστήσετε SHA2 αν είναι δυνατόν, μπορεί να αλλάξει μετά την εγκατάσταση
heresyourpassword=Here\ του τον κωδικό πρόσβασής σας στο
directorypageadded=Προσθήκη καταλόγου σελίδας
smspinactive=PIN ελέγχονται ok: σας λογαριασμός είναι ενεργός!
passwordnelogin=Ο κωδικός πρόσβασης δεν πρέπει να είναι το ίδιο με σύνδεση
loginfailedfor=η σύνδεση απέτυχε για
tradeTaxflag=σημαία του φόρου
pleasenote=Σημειώστε ότι ο νέος σας λογαριασμός δημιουργείται και μπορεί να ενεργοποιηθεί από θα:
smslocked=Κλειδωμένος λογαριασμός για τον sms: Επικοινωνήστε με το διαχειριστή σας για να ξεκλειδώσετε!
admpass=admin κωδικού πρόσβασης
tradeHash=hash
languagechanged=Αλλάξει γλώσσα
youare=Είστε
pleaseactivate=Παρακαλούμε να ενεργοποιήσετε το λογαριασμό σας νέα Cclite
sameaccount=Δεν είναι δυνατό να μεταφορά για ίδιο λογαριασμό
openId=Ανοίξτε το αναγνωριστικό
currencysymbolerror=σφάλμα σύμβολο νομίσματος
tradevolumes=Εμπόριο τόμους ανά μήνα&lt;br&gt;(inc. αναμονής/άνοιγμα κ.λπ....)
om_users=Οι χρήστες
isuniquename=είναι ένα μοναδικό όνομα
userinfofor=Πληροφορίες χρήστη για
userLogin=σύνδεση όνομα
doesnotexist=δεν υπάρχει
august=Αύγουστος
february=Φεβρουαρίου
reject=Όχι!
mailtransactionresult=αποτέλεσμα συναλλαγών αλληλογραφίας
notadebit=δεν μια συναλλαγή χρέωσης
om_partners=Μητρώου εταίρους
newpassword=Ο νέος κωδικός πρόσβασης cclite
tradeType=Τύπος
clear=Σαφής
usetags=Χρησιμοποιήσετε τις ετικέτες ελεύθερης μορφής παρακάτω
merchantkeyerror=εμπορικά βασικό σφάλμα
emailexists=Email υπάρχει, πρέπει να είναι μοναδικό
overservicechargelimit=Επιπλέον χρέωση υπηρεσιών είναι μεγαλύτερη από το ρυθμισμένο όριο
mobphoneexists=Αριθμός κινητού τηλεφώνου ανήκει σε κάποιον άλλο, πρέπει να είναι μοναδικό
badstreet=Όνομα unlikely street
currencyrejected=Δημιουργία απορρίφθηκε&lt;br&gt;Το όνομα του νομίσματος υπάρχει
transactionlimitexceeded=Η συναλλαγή είναι μεγαλύτερο από το όριο για το εν λόγω μητρώο
configurationupdated=Ρύθμιση παραμέτρων updated
tradeItem=το στοιχείο
badpostcode=Ακατάλληλη μορφή Ταχυδρομικός κώδικας
tradeId=αναγνωριστικό
tradeMirror=καθρέφτης
baduriname=Το URI που πρέπει να της φόρμας http://domain/Cclite
november=Νοεμβρίου
smsdebitfor=SMS χρέωσης για
pages=Σελίδες
batchtransaction=Δέσμης συναλλαγής: βλέπε περιγραφή
servicechargeapplied=Επιπλέον χρέωση υπηρεσιών εφαρμόζονται
invalidcurrency=μη έγκυρο νόμισμα
october=Οκτωβρίου
smsinvalidsyntax=Μη έγκυρο μήνυμα πληρωμή SMS
wrongdbversion=Αναβάθμιση της βάσης δεδομένων να 4.0 ή παραπάνω απαιτείται:
om_openid=Άνοιγμα αναγνωριστικά
suppliedwhen=και ο κωδικός πρόσβασης είναι εκείνη που δώσατε κατά την εγγραφή.
viagpgemail=Μέσω Email ΠΔΑ:
postemail=δημοσίευση διακινήσεις Email
userinactive=Χρήστης ανενεργό
dbpasswordorser=Βάση δεδομένων τον κωδικό πρόσβασης ή το χρήστη όνομα πρόβλημα:
chargetype=Χρέωση μοντέλο
ipaddressnotfound=Αυτή η διεύθυνση IP δεν βρίσκεται στη λίστα των διευθύνσεων ip που επιτρέπεται
viabatch=Μέσω δέσμης:
newpassword1=νέος κωδικός πρόσβασης
userexists=Χρήστης Exists, Παρακαλώ επιλέξτε κάποιο άλλο
validaccountname=είναι ένα όνομα έγκυρη/μοναδικό λογαριασμό
smspinfail=Μη έγκυρο αριθμό PIN: please try again!
error=για κατά λάθος
badcommitlimit=Δέσμευση όριο πρέπει να είναι αριθμητικό
useradded=Χρήστης προσθέσει
noencryptednotification=κοινοποίηση: Κρυπτογράφηση κλειδιού λείπει ή μη έγκυρο
userEmail=ηλεκτρονικό ταχυδρομείο
during=κατά τη διάρκεια
smsnopindetected=Αριθμός pin δεν βρεθεί, χρειάζεται ένα pin!
passwordsent=Ο κωδικός πρόσβασης αποστέλλονται στη διεύθυνση ηλεκτρονικού ταχυδρομείου σας (θα μπορούσε να φάκελο Ανεπιθύμητη αλληλογραφία!!!)
openiderror=Ανοίξτε το αναγνωριστικό σφάλματος:
passwordfailedfor=κωδικός πρόσβασης απέτυχε για
not_accepted=για δεν γίνονται δεκτές
accepted=για αποδοχή
openIdDesc=Ανοίξτε το αναγνωριστικό περιγραφή
nonexistentpartner=Εταίρος μητρώου δεν υπάρχει
smsnoorigin=Κανένας χρήστης Αποστολή sms που βρέθηκαν
invalidregistry=Μη έγκυρη μητρώου
bademail=Μη έγκυρη διεύθυνση ηλεκτρονικού ταχυδρομείου
smsoriginblank=Καταγωγής, ο αριθμός τηλεφώνου δεν βρέθηκε
tradeTitle=Τίτλος
putcursoron=Θέσει δρομέα σε αριθμό για να λάβετε διαφημίσεων Τίτλος
mailtransactions=αλληλογραφίας συναλλαγών
unknowncurrency=Άγνωστη νόμισμα
blankregistry=κενό μητρώου
badphone=Μη έγκυρος αριθμός για το κινητό τηλέφωνο
new=Νέα
matched=αντιστοίχιση
nosource=Δεν λογαριασμού προέλευσης για συναλλαγή
tryagain=Δοκίμασε ξανά?
emailnotfound=Ηλεκτρονικό ταχυδρομείο δεν βρέθηκε
show=Εμφάνιση
unknownregistry=Άγνωστο σφάλμα μητρώου ή βάσης δεδομένων
per=ανά
notanadmin=Δεν είστε ο διαχειριστής
invalidaccount=πρέπει να περιέχουν a-z, μόνο 1-9
balance=Ισορροπία
noremotecurrency=Νόμισμα δεν στο απομακρυσμένο μητρώο
cancel=Άκυρο
loginfirst=Παρακαλούμε, εισέλθετε στο πρώτο!
fieldvalueplease=τιμή του πεδίου παρακαλώ
september=Σεπτεμβρίου
batchfileproblems=Αυτά τα αρχεία δέσμης έχουν προβλήματα, χρησιμοποιήσετε επεξήγηση του ποντικιού για να δείτε:
regmanager=Διαχείριση μητρώου
directorylisting=Λίστα καταλόγων
unknownsender=Άγνωστος αποστολέας
rdfupdate=Ενημερώθηκε RSS feeds σε
nowlogonandcreate=Σύνδεση ως διαχειριστή τώρα και να δημιουργήσετε ένα νόμισμα
zerovaluetransaction=μηδενική αξία συναλλαγής δεν επιτρέπεται
statsupdate=Στατιστικά ενημέρωση στις
smserror=Παρουσιάστηκε σφάλμα SMS
invalidlogin=Το όνομα χρήστη περιέχει διαστήματα ή χαρακτήρες, απαγορευμένη
transactionstatusnow=Η κατάσταση της συναλλαγής είναι τώρα
isnotactive=δεν είναι ενεργό: επιβεβαίωση ή επικοινωνήστε με το διαχειριστή
manufacturererror=σφάλμα του κατασκευαστή
smstransactionemailtitle=Συναλλαγή Cclite SMS
confirm=Επιβεβαίωση
april=Απριλίου
om_categories=Κατηγορίες διαφημίσεων
tradeCurrency=νόμισμα
at=σε
modify=Τροποποίηση
ccinstallinsecure=ccinstall.CGI παρόντες και εκτελέσιμο, αυτό είναι πολύ επισφαλής, please remove
pinconfirmdifferent=PIN και PIN επιβεβαίωσης πρέπει να είναι το ίδιο
configordbproblem=το πρόβλημα ρύθμισης παραμέτρων ή βάσης δεδομένων: λάθος χρήστη ή τον κωδικό πρόσβασης;
ccsoapserverinsecure=ccserver.CGI παρόντες και εκτελέσιμο, αυτό είναι επισφαλής, please remove εκτός εάν χρησιμοποιηθεί
isnowactive=τώρα είναι ενεργή
openidnotfound=Ανοίξτε το αναγνωριστικό δεν βρέθηκε στο μητρώο
june=Ιουνίου
usepassword=Διορθώστε όνομα χρήστη βάσης δεδομένων/κωδικού πρόσβασης στο cclite.cf
viamail=Μέσω Email:
unknownrecipient=Άγνωστο παραλήπτη
mysqlnotrunning=MySQL πιθανώς δεν εκτελείται, παρακαλώ έναρξης διακομιστή
usernameis=Είναι το όνομα χρήστη σας
